version: '3.8'
services:
  web:
    build: ./frontend
    ports:
      - "80:80"
  flask-app:
    build: ./backend
    ports:
      - "5001:5001"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
