name: Build & Push

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:            # repo-scoped GITHUB_TOKEN
      contents: read        # (read is enough for checkout)
      packages: write       # allow image push
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      # Optional but handy – generates tags & adds the OCI label
      - name: Metadata for GHCR
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/csherman.net
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
